USE MASTER
GO

IF EXISTS(SELECT * FROM SYSDATABASES WHERE NAME = 'FACSQL') 
	DROP DATABASE FACSQL
GO
CREATE DATABASE FACSQL
GO

USE FACSQL
GO

CREATE TABLE MAE_EMIDOCELE(
	NID_EMIDOCELE INT IDENTITY(1,1) NOT NULL,
	NU_EMINUMRUC VARCHAR(11),
	NO_EMIRAZSOC VARCHAR(50),
	CO_EMICODAGE CHAR(4),
	NO_ESTEMIELE VARCHAR(30),
	NO_CONEMIELE VARCHAR(50),
	NO_EMIUBIGEO CHAR(6),
	NO_EMIDEPART VARCHAR(50),
	NO_EMIPROVIN VARCHAR(50),
	NO_EMIDISTRI VARCHAR(50),
	NO_EMIDIRFIS VARCHAR(500),
	NO_BASTIPBAS VARCHAR(50),
	NO_BASNOMSRV VARCHAR(150),
	NO_BASNOMBAS VARCHAR(50),
	NO_BASUSRBAS VARCHAR(50),
	NO_BASUSRPAS VARCHAR(100),
	NO_TABFACCAB VARCHAR(50),
	NO_TABFACDET VARCHAR(50),
	NO_RUTCERDIG VARCHAR(800),
	NO_USUSOLSUN VARCHAR(500),
	NO_PASSOLSUN VARCHAR(500),
	NID_CFGSEREMI INT,
	--
	FE_REGCREACI DATETIME,
	FE_REGMODIFI DATETIME,
	FL_REGINACTI CHAR(1),
	CONSTRAINT PK_EMIDOCELE_NID_EMIDOCELE PRIMARY KEY (NID_EMIDOCELE),
)
GO

CREATE TABLE MAE_CFGSEREMI(
	NID_CFGSEREMI INT IDENTITY(1,1),
	CO_IDENTIFICA VARCHAR(100),
	NO_IDENTIFICA VARCHAR(100),
	CO_DOCTIPDOC CHAR(2),
	CO_DOCPREFIJ CHAR(2),
	NU_DOCFORMAT INT,
	NU_DOCINICIA INT,
	NU_DOCFINALI INT,
	NU_DOCACTUAL INT,
	NID_EMIDOCELE INT,
	--
	FE_REGCREACI DATETIME,
	FE_REGMODIFI DATETIME,
	FL_REGINACTI CHAR(1),
	CONSTRAINT PK_CFGSEREMI_NID_CFGSEREMI PRIMARY KEY (NID_CFGSEREMI),
	CONSTRAINT FK_CFGSEREMI_EMIDOCELE_NID_EMIDOCELE FOREIGN KEY (NID_EMIDOCELE) REFERENCES MAE_EMIDOCELE(NID_EMIDOCELE)
)
GO

CREATE TABLE TBL_DOCELECAB(
	NID_DOCELECAB INT IDENTITY(1,1) NOT NULL,
	NU_DOCSERSUN VARCHAR(10),
	NU_DOCNUMSUN VARCHAR(10),
	FE_DOCFECEMI DATETIME,
	HO_DOCHOREMI CHAR(8),
	CO_DOCTIPDOC CHAR(2),
	CO_DOCTIPMND CHAR(3),
	FE_DOCFECVEN DATETIME,
	CO_EMITIPDOC CHAR(1),
	NU_EMINUMRUC VARCHAR(11),
	NO_EMINOMCOM VARCHAR(1500),
	NO_EMIRAZSOC VARCHAR(1500),
	NO_EMIDOMDIR VARCHAR(200),
	NO_EMIDOMURB VARCHAR(25),
	NO_EMIDOMPRV VARCHAR(30),
	CO_EMIDOMUBI CHAR(6),
	NO_EMIDOMDEP VARCHAR(30),
	NO_EMIDOMDIS VARCHAR(30),
	CO_EMIDOMPAI CHAR(2),
	FL_VENTAITIN CHAR(1),
	NO_ITNDIRCOM VARCHAR(200),
	NO_ITNURBANI VARCHAR(25),
	NO_ITNPROVIN VARCHAR(30),
	CO_ITNCODUBI CHAR(6),
	NO_ITNDEPART VARCHAR(30),
	NO_ITNDISTRI VARCHAR(30),
	CO_ITNCODPAI CHAR(2),
	FL_VENTAEXPO CHAR(1),
	CO_EXPCODPAI CHAR(2),
	CO_EMICODANE CHAR(4),
	CO_RECTIPDOC CHAR(1),
	NU_RECNUMDOC VARCHAR(15),
	NO_RECRAZSOC VARCHAR(1500),
	CO_REMTIPDOC CHAR(2),
	NU_REMNUMDOC VARCHAR(30),
	FL_REFADIDOC CHAR(1),
	MT_TOTMONIMP DECIMAL(12,2),
	MT_TOTVENEXP DECIMAL(12,2),
	MT_TOTIMPEXP DECIMAL(12,2),
	CO_CODTRIEXP CHAR(4),
	MT_TOTVENINA DECIMAL(12,2),
	MT_TOTIMPINA DECIMAL(12,2),
	CO_CODTRIINA CHAR(4),
	MT_TOTVENEXO DECIMAL(12,2),
	MT_TOTIMPEXO DECIMAL(12,2),
	CO_CODTRIEXO CHAR(4),
	MT_TOTVENGRA DECIMAL(12,2),
	MT_TOTIMPGRA DECIMAL(12,2),
	CO_CODTRIGRA CHAR(4),
	MT_TOTVENGRV DECIMAL(12,2),
	MT_TOTIMPGRV DECIMAL(12,2),
	CO_CODTRIGRV CHAR(4),
	MT_ISCMONBAS DECIMAL(12,2),
	MT_TOTMONISC DECIMAL(12,2),
	FL_CARGODESC VARCHAR(5),
	CO_CODCARDES CHAR(2),
	PO_CARDESPRC DECIMAL(12,5),
	MT_MONCARDES DECIMAL(12,2),
	MT_CARDESBAS DECIMAL(12,2),
	MT_TOTMONDES DECIMAL(12,2),
	MT_TOTMONCAR DECIMAL(12,2),
	MT_TOTIMPORT DECIMAL(12,2),
	MT_TOTVALVEN DECIMAL(12,2),
	MT_TOTPREVEN DECIMAL(12,2),
	CO_ADILEYEND CHAR(4),
	TX_ADIDESLEY VARCHAR(200),
	CO_ADITIPOPE CHAR(4),
	FL_PERCEPCIO CHAR(1),
	NO_PERINCADE VARCHAR(5),
	CO_PERREASON CHAR(2),
	PO_PERPORAPL DECIMAL(12,5),
	MT_PERMONPER DECIMAL(12,2),
	MT_PERBASIMP DECIMAL(12,2),
	FL_ANTICIPOS CHAR(1),
	MT_TOTMONANT DECIMAL(12,2),
	CO_GUIARUBIG CHAR(6),
	NO_GUIARDIRE VARCHAR(200),
	NO_GUIARURBA VARCHAR(25),
	NO_GUIARPROV VARCHAR(30),
	NO_GUIARDEPA VARCHAR(30),
	NO_GUIARDIST VARCHAR(30),
	CO_GUIARPAIS CHAR(2),
	FL_DETRACCIO CHAR(1),
	CO_DTRCODBIE CHAR(3),
	NO_DTRCUEBAN VARCHAR(100),
	MT_DTRMONDTR DECIMAL(12,2),
	PO_DTRPRCDTR DECIMAL(12,5),
	CO_SUNESTENV CHAR(2),
	TX_SUNRESENV VARCHAR(8000),
	FL_SUNDOCXML CHAR(1),
	XM_SUNDOCXML VARCHAR(MAX),
	FL_SUNDOCPDF CHAR(1),
	B6_SUNDOCPDF VARCHAR(MAX),
	FL_SUNDOCCDR CHAR(1),
	B6_SUNDOCCDR VARCHAR(MAX),
	--
	FE_REGCREACI DATETIME,
	FE_REGMODIFI DATETIME,
	FL_REGINACTI CHAR(1),
	CONSTRAINT PK_DOCELECAB_NID_DOCELECAB PRIMARY KEY (NID_DOCELECAB)
)
GO

CREATE TABLE INT_DOCELECAB(
	[F5_CRUCEMI] [char](11) NOT NULL,
	[F5_CCODAGE] [char](4) NOT NULL,
	[F5_CTD] [char](2) NOT NULL,
	[F5_CNUMSER] [char](4) NOT NULL,
	[F5_CNUMDOC] [char](7) NOT NULL,
	[F5_CNROPED] [char](11) NOT NULL,
	[F5_DFECDOC] [datetime] NULL,
	[F5_DFECVEN] [datetime] NULL,
	[F5_CDH] [char](1) NOT NULL,
	[F5_CVENDE] [char](5) NOT NULL,
	[F5_CNROCAJ] [char](5) NOT NULL,
	[F5_CCODCLI] [char](18) NOT NULL,
	[F5_CNOMBRE] [varchar](80) NOT NULL,
	[F5_CDIRECC] [varchar](80) NOT NULL,
	[F5_CRUC] [char](18) NOT NULL,
	[F5_CALMA] [char](4) NOT NULL,
	[F5_CFORVEN] [char](3) NOT NULL,
	[F5_CCODMON] [char](2) NOT NULL,
	[F5_NTIPCAM] [numeric](11, 4) NOT NULL,
	[F5_NIMPORT] [numeric](13, 2) NOT NULL,
	[F5_NIMPIGV] [numeric](11, 2) NOT NULL,
	[F5_NSALDO] [numeric](13, 2) NOT NULL,
	[F5_NDESCTO] [numeric](11, 2) NOT NULL,
	[F5_CNUMORD] [char](20) NOT NULL,
	[F5_CRFTD] [char](2) NOT NULL,
	[F5_CRFNSER] [char](4) NOT NULL,
	[F5_CRFNDOC] [char](20) NOT NULL,
	[F5_CGLOSA] [varchar](80) NOT NULL,
	[F5_CESTADO] [char](1) NOT NULL,
	[F5_CFACGUI] [char](1) NOT NULL,
	[F5_CCODTRA] [char](18) NOT NULL,
	[F5_CCENCOS] [char](6) NOT NULL,
	[F5_CCODMAQ] [char](18) NOT NULL,
	[F5_CDESTIN] [char](4) NOT NULL,
	[F5_CTF] [char](2) NOT NULL,
	[F5_CTIPANE] [char](1) NOT NULL,
	[F5_CANEREF] [char](18) NOT NULL,
	[F5_NPORDE1] [numeric](5, 2) NOT NULL,
	[F5_NPORDE2] [numeric](5, 2) NOT NULL,
	[F5_NFLETE] [numeric](9, 2) NOT NULL,
	[F5_NEMBAL] [numeric](9, 2) NOT NULL,
	[F5_NTASA] [numeric](9, 2) NOT NULL,
	[F5_CUSUOPE] [char](5) NOT NULL,
	[F5_CUSUSEC] [char](5) NOT NULL,
	[F5_CCODCAD] [char](4) NOT NULL,
	[F5_CCODINT] [char](10) NOT NULL,
	[F5_CCODAUT] [varchar](15) NOT NULL,
	[F5_CREPA] [char](1) NOT NULL,
	[F5_CUSUCRE] [char](5) NOT NULL,
	[F5_DFECCRE] [datetime] NULL,
	[F5_CUSUMOD] [char](5) NOT NULL,
	[F5_DFECMOD] [datetime] NULL,
	[F5_CTNC] [char](2) NOT NULL,
	[F5_CLINEA] [char](4) NOT NULL,
	[F5_CIMPRE] [char](1) NOT NULL,
	[F5_CCJENC] [char](1) NOT NULL,
	[F5_CVENDE2] [char](5) NOT NULL,
	[F5_NPORVEN] [numeric](6, 2) NOT NULL,
	[F5_NPORVE2] [numeric](6, 2) NOT NULL,
	[F5_CPERIOD] [char](10) NOT NULL,
	[F5_CRFTD2] [char](2) NOT NULL,
	[F5_CRFNDO2] [char](24) NOT NULL,
	[F5_DFECANU] [datetime] NULL,
	[F5_CTIPDNC] [char](1) NOT NULL,
	[F5_CCODVEH] [char](18) NOT NULL,
	[F5_CCODFER] [char](18) NOT NULL,
	[F5_CTIPDEV] [char](1) NOT NULL,
	[F5_CSUBDIA] [char](4) NOT NULL,
	[F5_CCOMPRO] [char](6) NOT NULL,
	[F5_DFECENT] [datetime] NULL,
	[F5_CNROPLA] [char](20) NOT NULL,
	[F5_CAGEOT] [char](4) NOT NULL,
	[F5_CORDTRA] [char](11) NOT NULL,
	[F5_CCHASIS] [char](18) NOT NULL,
	[F5_CHRADOC] [char](10) NOT NULL,
	[F5_CCOSUPV] [char](5) NOT NULL,
	[F5_CFLGPLA] [char](1) NOT NULL,
	[F5_CTORIGEN] [char](10) NOT NULL,
	[F5_CTDESTIN] [char](10) NOT NULL,
	[F5_CMONPER] [char](2) NOT NULL,
	[F5_NIMPPER] [numeric](13, 2) NOT NULL,
	[F5_CGUIFAC] [char](1) NOT NULL,
	[F5_AVANEXO] [char](1) NOT NULL,
	[F5_ACODANE] [char](18) NOT NULL,
	[F5_CCONTRAT] [char](20) NOT NULL,
	[F5_COBRA] [char](10) NOT NULL,
	[F5_CPERIOC] [char](15) NOT NULL,
	[F5_CCERTIF] [char](10) NOT NULL,
	[F5_CCODTAL] [char](4) NOT NULL,
	[F5_CTIPFOR] [char](2) NOT NULL,
	[F5_NPORPER] [numeric](8, 2) NOT NULL,
	[F5_DFECREF] [datetime] NULL,
	[F5_CMORFTC] [char](2) NOT NULL,
	[F5_NTCREF] [numeric](13, 4) NOT NULL,
	[F5_CNCAPLI] [char](1) NOT NULL,
	[F5_COD_ESTADO_SUNAT] [int] NULL,
	[F5_MENSAJE_SUNAT] [varchar](500) NULL,
	[F5_ESTADO_ENVIO] [int] NULL,
	[F5_XML] [varchar](250) NULL,
	[F5_CDR] [varchar](250) NULL,
	[F5_PDF] [varchar](250) NULL,
 CONSTRAINT [PK_INTDOCELECAB] PRIMARY KEY CLUSTERED 
(
	[F5_CRUCEMI] ASC,
	[F5_CCODAGE] ASC,
	[F5_CTD] ASC,
	[F5_CNUMSER] ASC,
	[F5_CNUMDOC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE INT_DOCELEDET(
	[F6_CRUCEMI] [char](11) NOT NULL,
	[F6_CCODAGE] [char](4) NOT NULL,
	[F6_CTD] [char](2) NOT NULL,
	[F6_CNUMSER] [char](4) NOT NULL,
	[F6_CNUMDOC] [char](7) NOT NULL,
	[F6_CITEM] [char](4) NOT NULL,
	[F6_CCODIGO] [char](25) NOT NULL,
	[F6_CDESCRI] [varchar](60) NOT NULL,
	[F6_CTR] [char](1) NOT NULL,
	[F6_NCANTID] [numeric](11, 3) NOT NULL,
	[F6_CUNIDAD] [char](3) NOT NULL,
	[F6_CSERIE] [char](18) NOT NULL,
	[F6_NCANREF] [numeric](10, 2) NOT NULL,
	[F6_NUNXENV] [numeric](8, 3) NOT NULL,
	[F6_NNUMENV] [numeric](7, 2) NOT NULL,
	[F6_NSALDAR] [numeric](11, 3) NOT NULL,
	[F6_NPRECIO] [numeric](18, 9) NOT NULL,
	[F6_NPRECI1] [numeric](18, 9) NOT NULL,
	[F6_NPREIMP] [numeric](20, 9) NOT NULL,
	[F6_NPREIM1] [numeric](20, 9) NOT NULL,
	[F6_NPRSIGV] [numeric](20, 9) NOT NULL,
	[F6_NDESCTO] [numeric](11, 2) NOT NULL,
	[F6_NDESDOC] [numeric](11, 2) NOT NULL,
	[F6_NVALDIS] [numeric](14, 4) NOT NULL,
	[F6_NIGVPOR] [numeric](5, 2) NOT NULL,
	[F6_NIGV] [numeric](11, 2) NOT NULL,
	[F6_NIMPUS] [numeric](13, 2) NOT NULL,
	[F6_NIMPMN] [numeric](13, 2) NOT NULL,
	[F6_CTIPITM] [char](3) NOT NULL,
	[F6_NPORDE1] [numeric](6, 2) NOT NULL,
	[F6_NIMP01] [numeric](10, 2) NOT NULL,
	[F6_NPORDE2] [numeric](6, 2) NOT NULL,
	[F6_NIMP02] [numeric](10, 2) NOT NULL,
	[F6_NPORDE3] [numeric](6, 2) NOT NULL,
	[F6_NIMP03] [numeric](10, 2) NOT NULL,
	[F6_NPORDE4] [numeric](6, 2) NOT NULL,
	[F6_NIMP04] [numeric](10, 2) NOT NULL,
	[F6_NPORDE5] [numeric](6, 2) NOT NULL,
	[F6_NIMP05] [numeric](10, 2) NOT NULL,
	[F6_NPORDES] [numeric](6, 2) NOT NULL,
	[F6_CESTADO] [char](1) NOT NULL,
	[F6_CVENDE] [char](5) NOT NULL,
	[F6_CALMA] [char](4) NOT NULL,
	[F6_CNROCAJ] [char](5) NOT NULL,
	[F6_CSTOCK] [char](1) NOT NULL,
	[F6_DFECDOC] [datetime] NULL,
	[F6_CCODLIN] [char](4) NOT NULL,
	[F6_CNROTAB] [char](6) NOT NULL,
	[F6_CNUMPAQ] [char](4) NOT NULL,
	[F6_CNDSCF] [char](8) NOT NULL,
	[F6_CNDSCL] [char](8) NOT NULL,
	[F6_CNDSCA] [char](8) NOT NULL,
	[F6_CNDSCB] [char](8) NOT NULL,
	[F6_CNFLAT] [char](8) NOT NULL,
	[F6_NPORCOM] [numeric](6, 2) NOT NULL,
	[F6_NIMPCOM] [numeric](10, 2) NOT NULL,
	[F6_CUSUCRE] [char](5) NOT NULL,
	[F6_DFECCRE] [datetime] NULL,
	[F6_NPRESIS] [numeric](18, 9) NOT NULL,
	[F6_CVENDE2] [char](5) NOT NULL,
	[F6_CITEMP] [char](4) NOT NULL,
	[F6_NTEMPER] [numeric](11, 2) NOT NULL,
	[F6_NISCPOR] [numeric](5, 2) NOT NULL,
	[F6_NISC] [numeric](11, 2) NOT NULL,
	[F6_NCANDEV] [numeric](11, 3) NOT NULL,
	[F6_CCENCOS] [char](6) NOT NULL,
	[F6_CANEXO] [char](18) NOT NULL,
	[F6_CANEREF] [char](18) NOT NULL,
	[F6_NCANDEC] [numeric](18, 9) NOT NULL,
	[F6_CTIPPLA] [char](2) NOT NULL,
	[F6_CCODPLA] [char](4) NOT NULL,
	[F6_CTIPCAT] [char](2) NOT NULL,
	[F6_CNROPLA] [char](20) NOT NULL,
	[F6_CCOSUPV] [char](5) NOT NULL,
	[F6_AVANEXO] [char](1) NOT NULL,
	[F6_ACODANE] [char](18) NOT NULL,
	[F6_NRETGAR] [numeric](18, 4) NOT NULL,
	[F6_CTIPDOC] [char](2) NOT NULL,
	[F6_CNRODOC] [char](11) NOT NULL,
	[F6_NTASRCN] [numeric](6, 2) NOT NULL,
	[F6_NIMPRCN] [numeric](15, 2) NOT NULL,
	[F6_CVANEXO] [char](1) NOT NULL,
	[F6_CCODANE] [char](18) NOT NULL,
	[F6_CCODAN2] [char](18) NOT NULL,
	[F6_CVANEX2] [char](1) NOT NULL,
	[F6_NPORCM1] [numeric](3, 0) NOT NULL,
	[F6_NPORCM2] [numeric](3, 0) NOT NULL,
	[F6_CISCTIP] [char](2) NOT NULL,
	[F6_NISCMON] [numeric](6, 2) NOT NULL,
	[F6_NISCPRE] [numeric](5, 2) NOT NULL,
 CONSTRAINT [PK_INTDOCELEDET] PRIMARY KEY CLUSTERED 
(
	[F6_CRUCEMI] ASC,
	[F6_CCODAGE] ASC,
	[F6_CTD] ASC,
	[F6_CNUMSER] ASC,
	[F6_CNUMDOC] ASC,
	[F6_CITEM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE TBL_DOCELEREF(
	NID_DOCELEREF INT IDENTITY(1,1),
	NU_REFDOCORG VARCHAR(40),
	CO_REFTIPDOC CHAR(2),
	NU_REFNUMDOC VARCHAR(30),
	--
	FE_REGCREACI DATETIME,
	FE_REGMODIFI DATETIME,
	FL_REGINACTI CHAR(1),
	NID_DOCELECAB INT,
	CONSTRAINT PK_DOCELEREF_NID_DOCELEREF PRIMARY KEY (NID_DOCELEREF),
	CONSTRAINT FK_DOCELEREF_DOCELECAB_NID_DOCELECAB FOREIGN KEY (NID_DOCELECAB) REFERENCES TBL_DOCELECAB (NID_DOCELECAB)
)
GO

CREATE TABLE TBL_DOCELEDET(
	NID_DOCELEDET INT IDENTITY(1,1),
	NU_DETORDITM VARCHAR(5),
	CO_DETUNDMED VARCHAR(3),
	QT_DETCANITM DECIMAL(12,10),
	CO_DETCODPRO VARCHAR(30),
	CO_DETCOPRSU VARCHAR(8),
	CO_DETCODGS1 VARCHAR(14),
	TX_DETDESITM VARCHAR(500),
	MT_DETVALUNI DECIMAL(12,10),
	MT_DETPREVEN DECIMAL(12,10),
	CO_DETCODPRE CHAR(2),
	MT_DETVALREF DECIMAL(12,10),
	CO_DETCOVARE CHAR(2),
	MT_DETTOTIMP DECIMAL(12,2),
	MT_AFEMONBAS DECIMAL(12,2),
	MT_AFEMONAFE DECIMAL(12,2),
	PO_AFEMONPRC DECIMAL(12,5),
	CO_AFEREASON VARCHAR(2),
	CO_AFECODTRI CHAR(4),
	MT_ISCMONBAS DECIMAL(12,2),
	MT_ISCMONAFE DECIMAL(12,2),
	PO_ISCMONPRC DECIMAL(12,5),
	CO_ISCTIPSIS CHAR(2),
	CO_ISCCODTRI CHAR(4),
	MT_DETVALVEN DECIMAL(12,2),
	NO_DETCARDES VARCHAR(5),
	CO_CARDESREA CHAR(2),
	DE_CARDESFAC DECIMAL(12,5),
	MT_CARDESMON DECIMAL(12,2),
	MT_CDEMONBAS DECIMAL(12,2),
	--
	FE_REGCREACI DATETIME,
	FE_REGMODIFI DATETIME,
	FL_REGINACTI CHAR(1),
	NID_DOCELECAB INT,
	CONSTRAINT PK_DOCELEDET_NID_DOCELEDET PRIMARY KEY (NID_DOCELEDET),
	CONSTRAINT FK_DOCELECAB_DOCELEDET_NID_DOCELECAB FOREIGN KEY (NID_DOCELECAB) REFERENCES TBL_DOCELECAB (NID_DOCELECAB)
)
GO

CREATE TABLE TL_PROFACINT(
	NID_PROFACINT INT IDENTITY(1,1),
	CO_ESTPROINT VARCHAR(30),
	NO_ESTPROINT VARCHAR(100),
	CO_TIPPROFAC VARCHAR(30),
	NO_TIPPROFAC VARCHAR(150),
	TX_DESCRIPCI VARCHAR(3000),
	--
	FE_REGCREACI DATETIME,
	FE_REGMODIFI DATETIME,
	FL_REGINACTI CHAR(1),
	NID_EMIDOCELE INT
	CONSTRAINT PK_PROMIGINT_NID_PROMIGINT PRIMARY KEY (NID_PROFACINT),
	CONSTRAINT FK_PROMIGINT_NID_EMIDOCELE FOREIGN KEY (NID_EMIDOCELE) REFERENCES MAE_EMIDOCELE(NID_EMIDOCELE)
)
GO

CREATE TABLE MAE_DATGENFAC(
	NID_DATGENFAC INT IDENTITY(1,1),
	NO_NOMMAEFAC VARCHAR(150),
	TX_DESMAEFAC VARCHAR(300),
	NO_CAMPOFAC1 VARCHAR(100),
	NO_CAMPOFAC2 VARCHAR(100),
	NO_CAMPOFAC3 VARCHAR(100),
	NO_CAMPOFAC4 VARCHAR(100),
	NO_CAMPOFAC5 VARCHAR(100),
	NO_CAMPOFAC6 VARCHAR(100),
	--
	FE_REGCREACI DATETIME,
	FE_REGMODIFI DATETIME,
	FL_REGINACTI CHAR(1),
	CONSTRAINT PK_DATGENFAC_NID_DATGENFAC PRIMARY KEY (NID_DATGENFAC)
)
GO
-- INSERCCIÓN DE DATOS
--
--MAESTROS
INSERT INTO MAE_DATGENFAC(NO_NOMMAEFAC, TX_DESMAEFAC, NO_CAMPOFAC1, NO_CAMPOFAC2, FE_REGCREACI, FL_REGINACTI)
VALUES('TIPPROINT', 'Guarda todos los tipos de procesos de la interface', 'MIG', 'Migración', GETDATE(), '0');
GO
--
INSERT INTO MAE_DATGENFAC(NO_NOMMAEFAC, TX_DESMAEFAC, NO_CAMPOFAC1, NO_CAMPOFAC2, FE_REGCREACI, FL_REGINACTI)
VALUES('ESTINTFAC', 'Guarda todos los estados en ejecución de la interface', 'CO', 'Correcto', GETDATE(), '0');
INSERT INTO MAE_DATGENFAC(NO_NOMMAEFAC, TX_DESMAEFAC, NO_CAMPOFAC1, NO_CAMPOFAC2, FE_REGCREACI, FL_REGINACTI)
VALUES('ESTINTFAC', 'Guarda todos los estados en ejecución de la interface', 'EJ', 'Ejecutando', GETDATE(), '0');
INSERT INTO MAE_DATGENFAC(NO_NOMMAEFAC, TX_DESMAEFAC, NO_CAMPOFAC1, NO_CAMPOFAC2, FE_REGCREACI, FL_REGINACTI)
VALUES('ESTINTFAC', 'Guarda todos los estados en ejecución de la interface', 'EX', 'Excepción', GETDATE(), '0');
GO
/*
--
INSERT INTO MAE_EMIDOCELE VALUES('20263019807', 'GRANOTEC PERU SA', '0001', 'ACTIVO', 'HABIDO', '150103', 'Lima', 'Lima', 'Ate', 'AV. LOS INGENIEROS NRO. 112 URB. - SANTA RAQUEL 2DA ETAPA', 'SQL', 'DESKTOP-U45U0IC\SQLEXPRESS', 'RSFACCAR', 'SA', 'A123456$', 'FT0001FACC', 'FT0001FACD', '', 'FACTURA1', 'FACTURA1', NULL, GETDATE(), NULL, '0');
INSERT INTO MAE_EMIDOCELE VALUES('20493098994', 'INVERSIONES INTI TUMI SOCIEDAD ANONIMA CERRADA', '0001', 'ACTIVO', 'HABIDO', '150116', 'Lima', 'Lima', 'Lince', 'JR. BERNARDO ALCEDO NRO. 329', 'SQL', 'DESKTOP-U45U0IC\SQLEXPRESS', 'RSFACCAR', 'SA', 'A123456$', 'FT0002FACC', 'FT0002FACD', '', 'FACTURA1', 'FACTURA1', NULL, GETDATE(), NULL, '0');
INSERT INTO MAE_EMIDOCELE VALUES('10074932903', 'ALVAREZ VARGAS JAVIER MAXIMILIANO', '0001', 'ACTIVO', 'HABIDO', '150115', 'Lima', 'Lima', 'La victoria', 'JR. GAMARRA NRO. 745 INT. 102', 'SQL', 'DESKTOP-U45U0IC\SQLEXPRESS', 'RSFACCAR', 'SA', 'A123456$', 'FT0003FACC', 'FT0003FACD', '', 'FACTURA1', 'FACTURA1', NULL, GETDATE(), NULL, '0');
INSERT INTO MAE_EMIDOCELE VALUES('20545756022', 'INVERSIONES INKA´S PALACE S.A.C.', '0001', 'ACTIVO', 'HABIDO', '150101', 'Lima', 'Lima', 'Lima', 'CAL. MANUEL DEL PINO NRO. 116 URB. - SANTA BEATRIZ', 'SQL', 'DESKTOP-U45U0IC\SQLEXPRESS', 'RSFACCAR', 'SA', 'A123456$', 'FT0005FACC', 'FT0005FACD', '', 'FACTURA1', 'FACTURA1', NULL, GETDATE(), NULL, '0');
GO
--
INSERT INTO MAE_CFGSEREMI VALUES('RESUMEN', 'RESUMEN DE BOLETAS','RC', 'RC', '0', 1, 1000, 0, 1, GETDATE(), NULL, '0');
INSERT INTO MAE_CFGSEREMI VALUES('COMUBAJ', 'COMUNICACIÓN DE BAJA','RA', 'RA', '0', 1, 1000, 0, 1, GETDATE(), NULL, '0');
INSERT INTO MAE_CFGSEREMI VALUES('RESUMEN', 'RESUMEN DE BOLETAS','RC', 'RC', '0', 1, 1000, 0, 2, GETDATE(), NULL, '0');
INSERT INTO MAE_CFGSEREMI VALUES('COMUBAJ', 'COMUNICACIÓN DE BAJA','RA', 'RA', '0', 1, 1000, 0, 2, GETDATE(), NULL, '0');
INSERT INTO MAE_CFGSEREMI VALUES('RESUMEN', 'RESUMEN DE BOLETAS','RC', 'RC', '0', 1, 1000, 0, 3, GETDATE(), NULL, '0');
INSERT INTO MAE_CFGSEREMI VALUES('COMUBAJ', 'COMUNICACIÓN DE BAJA','RA', 'RA', '0', 1, 1000, 0, 3, GETDATE(), NULL, '0');
INSERT INTO MAE_CFGSEREMI VALUES('RESUMEN', 'RESUMEN DE BOLETAS','RC', 'RC', '0', 1, 1000, 0, 4, GETDATE(), NULL, '0');
INSERT INTO MAE_CFGSEREMI VALUES('COMUBAJ', 'COMUNICACIÓN DE BAJA','RA', 'RA', '0', 1, 1000, 0, 4, GETDATE(), NULL, '0');
GO*/

--CREACION DE PROCEDURES

CREATE PROCEDURE SPS_SEG_GETERRINF
AS  
SELECT  
    ERROR_NUMBER() AS NU_ERRNUMBER
    ,ERROR_SEVERITY() AS NO_ERRSERVER
    ,ERROR_STATE() AS NO_ERROSTATE
    ,ERROR_PROCEDURE() AS NO_ERRORPROC
    ,ERROR_LINE() AS NU_ERRORLINE
    ,ERROR_MESSAGE() AS TX_ERRORMESS;  
GO

CREATE PROCEDURE SPS_MAE_EMIDOCELE
AS
BEGIN
	SELECT
		*
	FROM MAE_EMIDOCELE
	WHERE FL_REGINACTI = '0'
	ORDER BY FE_REGCREACI
END
GO

CREATE PROCEDURE SPS_TL_PROFACINT_BY_EMIDOCELE(
	@NID_EMIDOCELE INT,
	@CO_ESTPROINT VARCHAR(30),
	@CO_TIPPROFAC VARCHAR(30)
)
AS
BEGIN
	SELECT NID_EMIDOCELE, CO_ESTPROINT, CO_TIPPROFAC
	FROM TL_PROFACINT
	WHERE CO_ESTPROINT = @CO_ESTPROINT
	AND CO_TIPPROFAC = @CO_TIPPROFAC
	AND NID_EMIDOCELE = @NID_EMIDOCELE
	AND FL_REGINACTI = '0'
	ORDER BY FE_REGCREACI
END
GO

CREATE PROCEDURE SPI_TL_PROFACINT(
	@CO_TIPPROFAC VARCHAR(30), 
	@CO_ESTPROINT VARCHAR(30), 
	@NID_EMIDOCELE INT
)
AS
BEGIN
	DECLARE @NO_TRANSNAME VARCHAR(20);
	SELECT @NO_TRANSNAME = 'IPROFACINT'
	BEGIN TRANSACTION
	BEGIN TRY
		DECLARE @NO_TIPPROFAC VARCHAR(150),
				@NO_ESTPROINT VARCHAR(150)

		SELECT @NO_TIPPROFAC = TIPPROFAC.NO_CAMPOFAC2
		FROM MAE_DATGENFAC TIPPROFAC
		WHERE TIPPROFAC.NO_NOMMAEFAC = 'TIPPROINT'
		AND TIPPROFAC.NO_CAMPOFAC1 = @CO_TIPPROFAC
		AND TIPPROFAC.FL_REGINACTI = '0'

		SELECT @NO_ESTPROINT = ESTPROINT.NO_CAMPOFAC2
		FROM MAE_DATGENFAC ESTPROINT
		WHERE ESTPROINT.NO_NOMMAEFAC = 'ESTINTFAC'
		AND ESTPROINT.NO_CAMPOFAC1 = @CO_ESTPROINT
		AND ESTPROINT.FL_REGINACTI = '0'

		INSERT INTO TL_PROFACINT(CO_ESTPROINT, NO_ESTPROINT, CO_TIPPROFAC, NO_TIPPROFAC, FE_REGCREACI, NID_EMIDOCELE, TX_DESCRIPCI, FL_REGINACTI)
		SELECT @CO_ESTPROINT, @NO_ESTPROINT, @CO_TIPPROFAC, @NO_TIPPROFAC, GETDATE(), @NID_EMIDOCELE, 'Apertura de Nuevo Proceso en ejecución','0'
		
		
		IF @@TRANCOUNT > 0
		BEGIN
			COMMIT TRANSACTION @NO_TRANSNAME;
		END
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION @NO_TRANSNAME;
		EXEC SPS_SEG_GETERRINF;
	END CATCH
END
GO

CREATE PROCEDURE SPU_TL_PROFACINT(
	@CO_TIPPROFAC VARCHAR(30), 
	@CO_ESTPROINT VARCHAR(30), 
	@NID_EMIDOCELE INT,
	@TX_DESCRIPCI VARCHAR(3000) = NULL
)
AS
BEGIN
	DECLARE @NO_TRANSNAME VARCHAR(20);
	SELECT @NO_TRANSNAME = 'UPROFACINT'
	BEGIN TRANSACTION
	BEGIN TRY
		DECLARE @NO_ESTPROINT VARCHAR(150)

		SELECT @NO_ESTPROINT = ESTPROINT.NO_CAMPOFAC2
			FROM MAE_DATGENFAC ESTPROINT
			WHERE ESTPROINT.NO_NOMMAEFAC = 'ESTINTFAC'
			AND ESTPROINT.NO_CAMPOFAC1 = @CO_ESTPROINT
			AND ESTPROINT.FL_REGINACTI = '0'

		UPDATE TL_PROFACINT
			SET CO_ESTPROINT = @CO_ESTPROINT,
				NO_ESTPROINT = @NO_ESTPROINT,
				TX_DESCRIPCI = 
					CASE
						WHEN ISNULL(@TX_DESCRIPCI, '') <> '' THEN @TX_DESCRIPCI
						WHEN @CO_ESTPROINT = 'EX'  THEN  'Proceso Finalizado con errores'
						WHEN @CO_ESTPROINT = 'CO' THEN 'Proceso Finalizado correctamente'
					END,
				FE_REGMODIFI = GETDATE()
		WHERE NID_EMIDOCELE = @NID_EMIDOCELE
		AND CO_TIPPROFAC = @CO_TIPPROFAC
		AND CO_ESTPROINT = 'EJ'
		AND FL_REGINACTI = '0'
		IF @@TRANCOUNT > 0
		BEGIN
			COMMIT TRANSACTION @NO_TRANSNAME;
		END
	END TRY
	BEGIN CATCH
		EXEC SPS_SEG_GETERRINF;
	END CATCH
END
GO

CREATE PROCEDURE SPI_TBL_DOCELECD(
	@XM_EMIDOCELE XML,
	@XM_DOCELECAB XML,
	@XM_DOCELEDET XML
)
AS
BEGIN
	DECLARE @NO_TRANSNAME VARCHAR(20);
	SELECT @NO_TRANSNAME = 'IDOCELECD'
	--BEGIN TRANSACTION
	BEGIN TRY
		DECLARE @I_DOCEMI INT ,@I_DOCCAB INT, @I_DOCDET INT
		--Emisor
		-- Cabecera
		EXEC SP_XML_PREPAREDOCUMENT @I_DOCEMI OUTPUT, @XM_EMIDOCELE;
		SELECT	  *
		INTO #TMP_EMIDOCELE
		FROM  OPENXML (@I_DOCEMI, '/BEMaeemiele',2)
			WITH(
				nid_maeemiele INT,   
				nu_eminumruc VARCHAR(11),
				no_emirazsoc VARCHAR(50),
				no_estemiele VARCHAR(30),
				no_conemiele VARCHAR(50),
				no_emiubigeo CHAR(6),
				no_emidepart VARCHAR(50),
				no_emiprovin VARCHAR(50),
				no_emidistri VARCHAR(50),
				no_emidirfis VARCHAR(500),
				no_bastipbas VARCHAR(50),
				no_basnomsrv VARCHAR(150),
				no_basnombas VARCHAR(50),
				no_basusrbas VARCHAR(50),
				no_basusrpas VARCHAR(100),
				no_tabfaccab VARCHAR(50),
				no_tabfacdet VARCHAR(50),
				no_rutcerdig VARCHAR(800),
				fe_regcreaci DATETIME,   
				fe_regmodifi DATETIME,   
				fl_reginacti CHAR(1) 
			)
		EXEC SP_XML_PREPAREDOCUMENT @I_DOCCAB OUTPUT, @XM_DOCELECAB;
		SELECT    *  
		INTO #TMP_DOCELECAB
		FROM OPENXML (@I_DOCCAB, '/BEDoccabcli',2)
		 WITH (f5_ccodage CHAR(4),
				f5_ctd CHAR(2),
				f5_cnumser CHAR(4),
				f5_cnumdoc CHAR(7),
				f5_cnroped CHAR(11),
				f5_dfecdoc DATETIME,   
				f5_dfecven DATETIME,   
				f5_cdh CHAR(1),
				f5_cvende CHAR(5),
				f5_cnrocaj CHAR(5),
				f5_ccodcli CHAR(18),
				f5_cnombre VARCHAR(80),
				f5_cdirecc VARCHAR(80),
				f5_cruc CHAR(18),
				f5_calma CHAR(4),
				f5_cforven CHAR(3),
				f5_ccodmon CHAR(2),
				f5_ntipcam DECIMAL(12,2),
				f5_nimport DECIMAL(12,2),
				f5_nimpigv DECIMAL(12,2),
				f5_nsaldo DECIMAL(12,2),
				f5_ndescto DECIMAL(12,2),
				f5_cnumord CHAR(20),
				f5_crftd CHAR(2),
				f5_crfnser CHAR(4),
				f5_crfndoc CHAR(20),
				f5_cglosa VARCHAR(80),
				f5_cestado CHAR(1),
				f5_cfacgui CHAR(1),
				f5_ccodtra CHAR(18),
				f5_ccencos CHAR(6),
				f5_ccodmaq CHAR(18),
				f5_cdestin CHAR(4),
				f5_ctf CHAR(2),
				f5_ctipane CHAR(1),
				f5_caneref CHAR(18),
				f5_nporde1 DECIMAL(12,2),
				f5_nporde2 DECIMAL(12,2),
				f5_nflete DECIMAL(12,2),
				f5_nembal DECIMAL(12,2),
				f5_ntasa DECIMAL(12,2),
				f5_cusuope CHAR(5),
				f5_cususec CHAR(5),
				f5_ccodcad CHAR(4),
				f5_ccodint CHAR(10),
				f5_ccodaut VARCHAR(15),
				f5_crepa CHAR(1),
				f5_cusucre CHAR(5),
				f5_dfeccre DATETIME,   
				f5_cusumod CHAR(5),
				f5_dfecmod DATETIME,   
				f5_ctnc CHAR(2),
				f5_clinea CHAR(4),
				f5_cimpre CHAR(1),
				f5_ccjenc CHAR(1),
				f5_cvende2 CHAR(5),
				f5_nporven DECIMAL(12,2),
				f5_nporve2 DECIMAL(5),
				f5_cperiod CHAR(10),
				f5_crftd2 CHAR(2),
				f5_crfndo2 CHAR(24),
				f5_dfecanu DATETIME,   
				f5_ctipdnc CHAR(1),
				f5_ccodveh CHAR(18),
				f5_ccodfer CHAR(18),
				f5_ctipdev CHAR(1),
				f5_csubdia CHAR(4),
				f5_ccompro CHAR(6),
				f5_dfecent DATETIME,   
				f5_cnropla CHAR(20),
				f5_cageot CHAR(4),
				f5_cordtra CHAR(11),
				f5_cchasis CHAR(18),
				f5_chradoc CHAR(10),
				f5_ccosupv CHAR(5),
				f5_cflgpla CHAR(1),
				f5_ctorigen CHAR(10),
				f5_ctdestin CHAR(10),
				f5_cmonper CHAR(2),
				f5_nimpper DECIMAL(12,2),
				f5_cguifac CHAR(1),
				f5_avanexo CHAR(1),
				f5_acodane CHAR(18),
				f5_ccontrat CHAR(20),
				f5_cobra CHAR(10),
				f5_cperioc CHAR(15),
				f5_ccertif CHAR(10),
				f5_ccodtal CHAR(4),
				f5_ctipfor CHAR(2),
				f5_nporper DECIMAL(12,2),
				f5_dfecref DATETIME,   
				f5_cmorftc CHAR(2),
				f5_ntcref DECIMAL(12,2),
				f5_cncapli CHAR(1),
				f5_cod_estado_sunat INT,
				f5_mensaje_sunat VARCHAR(500),
				f5_estado_envio INT,
				f5_xml VARCHAR(250),
				f5_cdr VARCHAR(250),
				f5_pdf VARCHAR(250));
		EXEC SP_XML_PREPAREDOCUMENT @I_DOCDET OUTPUT, @XM_DOCELEDET;
		SELECT	  *
		INTO #TMP_DOCELEDET
		FROM  OPENXML (@I_DOCDET, '/ArrayOfBEDocdetcli/BEDocdetcli',2)
			WITH(f6_ccodage CHAR(4),
					f6_ctd CHAR(2),
					f6_cnumser CHAR(4),
					f6_cnumdoc CHAR(7),
					f6_citem CHAR(4),
					f6_ccodigo CHAR(25),
					f6_cdescri VARCHAR(60),
					f6_ctr CHAR(1),
					f6_ncantid NUMERIC(12,2),
					f6_cunidad CHAR(3),
					f6_cserie CHAR(18),
					f6_ncanref NUMERIC(12,2),
					f6_nunxenv NUMERIC(12,2),
					f6_nnumenv NUMERIC(12,2),
					f6_nsaldar NUMERIC(12,2),
					f6_nprecio NUMERIC(12,2),
					f6_npreci1 NUMERIC(12,2),
					f6_npreimp NUMERIC(12,2),
					f6_npreim1 NUMERIC(12,2),
					f6_nprsigv NUMERIC(12,2),
					f6_ndescto NUMERIC(12,2),
					f6_ndesdoc NUMERIC(12,2),
					f6_nvaldis NUMERIC(12,2),
					f6_nigvpor NUMERIC(12,2),
					f6_nigv NUMERIC(12,2),
					f6_nimpus NUMERIC(12,2),
					f6_nimpmn NUMERIC(12,2),
					f6_ctipitm CHAR(3),
					f6_nporde1 NUMERIC(12,2),
					f6_nimp01 NUMERIC(12,2),
					f6_nporde2 NUMERIC(12,2),
					f6_nimp02 NUMERIC(12,2),
					f6_nporde3 NUMERIC(12,2),
					f6_nimp03 NUMERIC(12,2),
					f6_nporde4 NUMERIC(12,2),
					f6_nimp04 NUMERIC(12,2),
					f6_nporde5 NUMERIC(12,2),
					f6_nimp05 NUMERIC(12,2),
					f6_npordes NUMERIC(12,2),
					f6_cestado CHAR(1),
					f6_cvende CHAR(5),
					f6_calma CHAR(4),
					f6_cnrocaj CHAR(5),
					f6_cstock CHAR(1),
					f6_dfecdoc DATETIME,   
					f6_ccodlin CHAR(4),
					f6_cnrotab CHAR(6),
					f6_cnumpaq CHAR(4),
					f6_cndscf CHAR(8),
					f6_cndscl CHAR(8),
					f6_cndsca CHAR(8),
					f6_cndscb CHAR(8),
					f6_cnflat CHAR(8),
					f6_nporcom NUMERIC(12,2),
					f6_nimpcom NUMERIC(12,2),
					f6_cusucre CHAR(5),
					f6_dfeccre DATETIME,
					f6_npresis NUMERIC(12,2),
					f6_cvende2 CHAR(5),
					f6_citemp CHAR(4),
					f6_ntemper NUMERIC(12,2),
					f6_niscpor NUMERIC(12,2),
					f6_nisc NUMERIC(12,2),
					f6_ncandev NUMERIC(12,2),
					f6_ccencos CHAR(6),
					f6_canexo CHAR(18),
					f6_caneref CHAR(18),
					f6_ncandec NUMERIC(12,2),
					f6_ctippla CHAR(2),
					f6_ccodpla CHAR(4),
					f6_ctipcat CHAR(2),
					f6_cnropla CHAR(20),
					f6_ccosupv CHAR(5),
					f6_avanexo CHAR(1),
					f6_acodane CHAR(18),
					f6_nretgar NUMERIC(12,2),
					f6_ctipdoc CHAR(2),
					f6_cnrodoc CHAR(11),
					f6_ntasrcn NUMERIC(12,2),
					f6_nimprcn NUMERIC(12,2),
					f6_cvanexo CHAR(1),
					f6_ccodane CHAR(18),
					f6_ccodan2 CHAR(18),
					f6_cvanex2 CHAR(1),
					f6_nporcm1 NUMERIC(12,2),
					f6_nporcm2 NUMERIC(12,2),
					f6_cisctip CHAR(2),
					f6_niscmon NUMERIC(12,2),
					f6_niscpre NUMERIC(12,2));

		--Insertando en tablas cabecera y detalle
		INSERT INTO INT_DOCELECAB
		SELECT emi.nu_eminumruc, cab.*
		FROM #TMP_EMIDOCELE emi
		CROSS JOIN #TMP_DOCELECAB cab

		INSERT INTO INT_DOCELEDET
		SELECT emi.nu_eminumruc, det.*
		FROM #TMP_EMIDOCELE emi
		CROSS JOIN #TMP_DOCELEDET det
		IF @@TRANCOUNT > 0
		BEGIN
			COMMIT TRANSACTION @NO_TRANSNAME;
		END
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION @NO_TRANSNAME;
		EXEC SPS_SEG_GETERRINF;
	END CATCH
END
GO

CREATE PROCEDURE SPS_GET_CORRELATIVO_MASIVOS(
	@NID_EMIDOCELE INT,
	@CO_DOCTIPDOC CHAR(2)
)
AS
BEGIN
	SELECT (ISNULL(MAX(NU_DOCACTUAL),0) + 1) AS CORRELATIVO FROM MAE_CFGSEREMI
	WHERE CONVERT(VARCHAR(10),FE_REGMODIFI,103) = CONVERT(VARCHAR(10),GETDATE(),103)
	AND CO_DOCTIPDOC = @CO_DOCTIPDOC
	AND NID_EMIDOCELE = @NID_EMIDOCELE
END
GO

CREATE PROCEDURE SPS_SET_CORRELATIVO_MASIVOS(
	@NID_EMIDOCELE INT,
	@CO_DOCTIPDOC CHAR(2),
	@NU_DOCNEOCOR INT
)
AS
BEGIN
	UPDATE MAE_CFGSEREMI
	SET NU_DOCACTUAL = @NU_DOCNEOCOR,
	FE_REGMODIFI = GETDATE()
	WHERE CO_DOCTIPDOC = @CO_DOCTIPDOC
	AND NID_EMIDOCELE = @NID_EMIDOCELE
END
GO